name = "ECMEDox"
uuid = "1437dc8d-fd17-40e7-b0f7-451a5e40c249"
version = "0.4.0"
authors = ["Wen-Wei Tseng <sosiristseng@gmail.com>"]

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"

[compat]
DiffEqCallbacks = "4.10.1"
DisplayAs = "0.1.6"
ModelingToolkit = "10.26.1"
NaNMath = "1.1.3"
NonlinearSolve = "4.12.0"
OrdinaryDiffEq = "6.103.0"
Plots = "1.41.1"
ProgressLogging = "0.1.5"
SteadyStateDiffEq = "2.8.0"
