name = "ECMEDox"
uuid = "1437dc8d-fd17-40e7-b0f7-451a5e40c249"
version = "0.4.0"
authors = ["Wen-Wei Tseng <sosiristseng@gmail.com>"]

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
